version: 1.2.1.{build}


os: Visual Studio 2015


# branches to build
branches:
  only:
  - master
  - dev


# Do not build on tags (GitHub only)
skip_tags: true


# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform:
#  - x86
#  - x64


environment:
  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release

  matrix:
  - platform: x86
    CMAKE_ARGS: -G"Visual Studio 14" -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\fayecpp-install-win-%PLATFORM% -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DFAYECPP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%

  - platform: x64
    CMAKE_ARGS: -G"Visual Studio 14 Win64" -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\fayecpp-install-win-%PLATFORM% -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DFAYECPP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%


configuration: Release


# clone directory
clone_folder: c:\dev\FayeCpp


# scripts that run after cloning repository
install:
  - cd c:\dev\FayeCpp
  - md fayecpp-install-win-%PLATFORM%
  - git submodule update --init --recursive


build:
  parallel: true
  verbosity: detailed


build_script:
  - cd c:\dev\FayeCpp
  - md build
  - cd build
  - cmake %CMAKE_ARGS% ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target INSTALL
  - ctest
  - cd ..


after_build:
  - 7z a -t7z -mx=9 FayeCpp-Win-%PLATFORM%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.7z c:\dev\FayeCpp\fayecpp-install-win-%PLATFORM%


artifacts:
  - path: '*.7z'


deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: 'Appveyor CI build artifacts. Compressed install path with binaries, libraries and configured headers'
    auth_token:
      secure: 9fCOXiEygRERkV9JN67Rqq6WFwdbSBIllYdZGYcSoFPj1oUAxk3aRi+bWv04l7M5
    artifact: /.*\.7z/
    draft: false
    prerelease: true
    on:
      branch: master
